Traceback (most recent call last):
  File "/home/imme/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/imme/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/imme/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/imme/miniconda3/envs/jupyterbook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/imme/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/imme/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/imme/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%run salary_age.ipynb
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [43mget_ipython[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mrun_line_magic[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mrun[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43msalary_age.ipynb[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2480[0m, in [0;36mInteractiveShell.run_line_magic[0;34m(self, magic_name, line, _stack_depth)[0m
[1;32m   2478[0m     kwargs[[38;5;124m'[39m[38;5;124mlocal_ns[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_local_scope(stack_depth)
[1;32m   2479[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[0;32m-> 2480[0m     result [38;5;241m=[39m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   2482[0m [38;5;66;03m# The code below prevents the output from being displayed[39;00m
[1;32m   2483[0m [38;5;66;03m# when using magics with decorator @output_can_be_silenced[39;00m
[1;32m   2484[0m [38;5;66;03m# when the last Python token in the expression is a ';'.[39;00m
[1;32m   2485[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(fn, magic[38;5;241m.[39mMAGIC_OUTPUT_CAN_BE_SILENCED, [38;5;28;01mFalse[39;00m):

File [0;32m~/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/IPython/core/magics/execution.py:737[0m, in [0;36mExecutionMagics.run[0;34m(self, parameter_s, runner, file_finder)[0m
[1;32m    735[0m     [38;5;28;01mwith[39;00m preserve_keys([38;5;28mself[39m[38;5;241m.[39mshell[38;5;241m.[39muser_ns, [38;5;124m'[39m[38;5;124m__file__[39m[38;5;124m'[39m):
[1;32m    736[0m         [38;5;28mself[39m[38;5;241m.[39mshell[38;5;241m.[39muser_ns[[38;5;124m'[39m[38;5;124m__file__[39m[38;5;124m'[39m] [38;5;241m=[39m filename
[0;32m--> 737[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mshell[49m[38;5;241;43m.[39;49m[43msafe_execfile_ipy[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mraise_exceptions[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m    738[0m     [38;5;28;01mreturn[39;00m
[1;32m    740[0m [38;5;66;03m# Control the response to exit() calls made by the script being run[39;00m

File [0;32m~/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3005[0m, in [0;36mInteractiveShell.safe_execfile_ipy[0;34m(self, fname, shell_futures, raise_exceptions)[0m
[1;32m   3003[0m result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mrun_cell(cell, silent[38;5;241m=[39m[38;5;28;01mTrue[39;00m, shell_futures[38;5;241m=[39mshell_futures)
[1;32m   3004[0m [38;5;28;01mif[39;00m raise_exceptions:
[0;32m-> 3005[0m     [43mresult[49m[38;5;241;43m.[39;49m[43mraise_error[49m[43m([49m[43m)[49m
[1;32m   3006[0m [38;5;28;01melif[39;00m [38;5;129;01mnot[39;00m result[38;5;241m.[39msuccess:
[1;32m   3007[0m     [38;5;28;01mbreak[39;00m

File [0;32m~/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/IPython/core/interactiveshell.py:308[0m, in [0;36mExecutionResult.raise_error[0;34m(self)[0m
[1;32m    306[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39merror_before_exec
[1;32m    307[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39merror_in_exec [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 308[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39merror_in_exec

    [0;31m[... skipping hidden 1 frame][0m

File [0;32m/tmp/ipykernel_11377/3443943555.py:1[0m
[0;32m----> 1[0m df [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_parquet[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m../data/SO_2014_2022.pq[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m df [38;5;241m=[39m df[(df[[38;5;124m'[39m[38;5;124mSalary[39m[38;5;124m'[39m] [38;5;241m>[39m [38;5;241m0[39m) [38;5;241m&[39m (df[[38;5;124m'[39m[38;5;124mSalary[39m[38;5;124m'[39m] [38;5;241m<[39m [38;5;241m250000[39m)]
[1;32m      4[0m df[38;5;241m.[39mhead()

File [0;32m~/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/pandas/io/parquet.py:651[0m, in [0;36mread_parquet[0;34m(path, engine, columns, storage_options, use_nullable_dtypes, dtype_backend, filesystem, filters, **kwargs)[0m
[1;32m    498[0m [38;5;129m@doc[39m(storage_options[38;5;241m=[39m_shared_docs[[38;5;124m"[39m[38;5;124mstorage_options[39m[38;5;124m"[39m])
[1;32m    499[0m [38;5;28;01mdef[39;00m [38;5;21mread_parquet[39m(
[1;32m    500[0m     path: FilePath [38;5;241m|[39m ReadBuffer[[38;5;28mbytes[39m],
[0;32m   (...)[0m
[1;32m    508[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs,
[1;32m    509[0m ) [38;5;241m-[39m[38;5;241m>[39m DataFrame:
[1;32m    510[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    511[0m [38;5;124;03m    Load a parquet object from the file path, returning a DataFrame.[39;00m
[1;32m    512[0m 
[0;32m   (...)[0m
[1;32m    648[0m [38;5;124;03m    1    4    9[39;00m
[1;32m    649[0m [38;5;124;03m    """[39;00m
[0;32m--> 651[0m     impl [38;5;241m=[39m [43mget_engine[49m[43m([49m[43mengine[49m[43m)[49m
[1;32m    653[0m     [38;5;28;01mif[39;00m use_nullable_dtypes [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m lib[38;5;241m.[39mno_default:
[1;32m    654[0m         msg [38;5;241m=[39m (
[1;32m    655[0m             [38;5;124m"[39m[38;5;124mThe argument [39m[38;5;124m'[39m[38;5;124muse_nullable_dtypes[39m[38;5;124m'[39m[38;5;124m is deprecated and will be removed [39m[38;5;124m"[39m
[1;32m    656[0m             [38;5;124m"[39m[38;5;124min a future version.[39m[38;5;124m"[39m
[1;32m    657[0m         )

File [0;32m~/miniconda3/envs/jupyterbook/lib/python3.10/site-packages/pandas/io/parquet.py:67[0m, in [0;36mget_engine[0;34m(engine)[0m
[1;32m     64[0m         [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m [38;5;28;01mas[39;00m err:
[1;32m     65[0m             error_msgs [38;5;241m+[39m[38;5;241m=[39m [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m - [39m[38;5;124m"[39m [38;5;241m+[39m [38;5;28mstr[39m(err)
[0;32m---> 67[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[1;32m     68[0m         [38;5;124m"[39m[38;5;124mUnable to find a usable engine; [39m[38;5;124m"[39m
[1;32m     69[0m         [38;5;124m"[39m[38;5;124mtried using: [39m[38;5;124m'[39m[38;5;124mpyarrow[39m[38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;124mfastparquet[39m[38;5;124m'[39m[38;5;124m.[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m     70[0m         [38;5;124m"[39m[38;5;124mA suitable version of [39m[38;5;124m"[39m
[1;32m     71[0m         [38;5;124m"[39m[38;5;124mpyarrow or fastparquet is required for parquet [39m[38;5;124m"[39m
[1;32m     72[0m         [38;5;124m"[39m[38;5;124msupport.[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m     73[0m         [38;5;124m"[39m[38;5;124mTrying to import the above resulted in these errors:[39m[38;5;124m"[39m
[1;32m     74[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00merror_msgs[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m     75[0m     )
[1;32m     77[0m [38;5;28;01mif[39;00m engine [38;5;241m==[39m [38;5;124m"[39m[38;5;124mpyarrow[39m[38;5;124m"[39m:
[1;32m     78[0m     [38;5;28;01mreturn[39;00m PyArrowImpl()

[0;31mImportError[0m: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.

